# config/packages/doctrine_migrations.yaml

doctrine_migrations:
  # List of namespace/path pairs to search for migrations, at least one required
  migrations_paths:
    'App\Services\Migrations': 'src/Services/Migrations'

  # Connection to use for the migrations
  em: default

  storage:
    # Default (SQL table) metadata storage configuration
    table_storage:
      table_name: 'doctrine_migration_versions'
      version_column_name: 'version'
      version_column_length: 190
      executed_at_column_name: 'executed_at'


  # Run all migrations in a transaction.
  all_or_nothing: true

  # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
  check_database_platform: true

  # Whether or not to wrap migrations in a single transaction.
  transactional: true

  # Whether or not to enable the profiler collector to calculate and visualize migration status. This adds some queries overhead.
  # enable_profiler: false
